### ISSUE TITLE
Quick Example

### ISSUE THREAD

**Issue by c0d1ng** [Muntaner/visjs_districts#1]
Could you please provide a short example on how to use these districts?
Thanks!

**Comment by Muntaner** [comment]
Hi @c0d1ng ,
as you can see in the randomized example, in order to use this feature you will need to define:
- the groups, each for distinct district of the network
- the nodes, which will be linked to a group
- the edges between the nodes, as you would do in a standard VisJS network

Then, in order to place the network node sin districts, you'll need to use the [computeNodesPositionsDistricts](https://github.com/Muntaner/visjs_districts/blob/master/js/draw.js#L33) passing the nodes and the groups and **disable the physics of the network** (this will prevent the physics engine of VisJS to replace the nodes on the canvas).
If you want to highlight the districts, you can optionally include the [afterNetworkDrawing](https://github.com/Muntaner/visjs_districts/blob/master/js/draw.js#L53) function as you can see in the _draw.js_ file.

A really basic example with networking concepts is the following:
`
const groups = ['network_1', 'network_2', 'network_3']

    const visNodes = [
        {
            id: 'node1',
            label: 'Computer 1',
            group: 'network_1'
        },
        {
            id: 'node2',
            label: 'Computer 2',
            group: 'network_1'
        },
        {
            id: 'node3',
            label: 'Computer 3',
            group: 'network_1'
        },
        {
            id: 'node4',
            label: 'Server',
            group: 'network_1'
        },

        {
            id: 'node5',
            label: 'Computer 1',
            group: 'network_2'
        },
        {
            id: 'node6',
            label: 'Computer 2',
            group: 'network_2'
        },
        {
            id: 'node7',
            label: 'Server',
            group: 'network_2'
        },

        {
            id: 'node8',
            label: 'Computer 1',
            group: 'network_3'
        },
        {
            id: 'node9',
            label: 'Computer 2',
            group: 'network_3'
        },
        {
            id: 'node10',
            label: 'Computer 3',
            group: 'network_3'
        },
        {
            id: 'node11',
            label: 'Computer 4',
            group: 'network_3'
        },
        {
            id: 'node12',
            label: 'Computer 5',
            group: 'network_3'
        }
    ]

    const visEdges = [
        {
            id: 'edge1',
            from: 'node1',
            to: 'node2'
        },
        {
            id: 'edge2',
            from: 'node1',
            to: 'node3'
        },
        {
            id: 'edge3',
            from: 'node3',
            to: 'node6'
        },
        {
            id: 'edge4',
            from: 'node8',
            to: 'node10'
        },
        {
            id: 'edge5',
            from: 'node11',
            to: 'node2'
        }
    ]

    nodes = new vis.DataSet()
    edges = new vis.DataSet()
    edges.add(visEdges)

    computeNodesPositionsDistricts(visNodes, groups)
    nodes.add(visNodes)

    var container = document.getElementById('districts-network')

    var data = {
        nodes: nodes,
        edges: edges
    }
    var options = {
        physics:
        {
            enabled: false
        }
    }
    network = new vis.Network(container, data, options)

    network.on('afterDrawing', (ctx) => afterNetworkDrawing(network, ctx))
...
`

This will generate three districts with some basic connections, as you can see in [this screenshot](https://i.imgur.com/zkUDbVU.png).

Has this been helpful?

**Comment by c0d1ng** [comment]
Thanks for the detailed example! This helped me a lot.
